require("items.apple")
require("items.menus")
require("items.aerospaces")
require("items.front_app")
-- require("items.reactive_space")
require("items.calendar")
require("items.widgets")
require("items.media")
require("items.brew")
require("items.vpn")
require("items.keyboard_layout")
require("items.svim")
