require("items.aerospace")
require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
require("items.widgets")
require("items.media")
require("items.keyboard_layout")
require("items.vpn")
require("items.npm_registry")
require("items.brew")
require("items.svim")

