#!/usr/bin/env bash

languages="ts\ntsx\ncss\njson\n"
LANG=$(
	echo -e "$languages" | fzf --prompt="Select a language: "
)

SG_PREFIX="sg --lang $LANG --pattern"
fzf --ansi \
	--disabled \
	--query "\$A" \
	--bind "change:reload:sleep 0.1; $SG_PREFIX {q} || true" \
	--delimiter : \
	--preview 'bat --color=always {1} --highlight-line {2}' \
	--preview-window 'up,60%,border-bottom,+{2}+3/3,~3' \
	--prompt "$LANG pattern > " \
	--header "type $LANG expression pattern ($A-Z => token, $$$ => tokens to skip)" \
	--bind 'enter:become(nvim "+call cursor({2},{3})" {1})'
