[keepassxc]
	database = "$HOME/Sync/Documents/keepass/pw.kdbx"
[git]
	autoCommit = false
[diff]
	command = "difft"
	args = ["{{ `{{ .Destination }}` }}", "{{ `{{ .Target }}` }}"]
[merge]
	command = "nvim"
	args = ["-d", "{{ `{{ .Source }}` }}", "{{ `{{ .Destination }}` }}", "{{ `{{ .Target }}` }}"]
